POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "username1",
  "email": "username1@example.com",
  "passwordHash": "username1"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "username2",
  "email": "username2@example.com",
  "passwordHash": "username2"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "username3",
  "email": "username3@example.com",
  "passwordHash": "username3"
}